# Generated by Django 6.1 on 2026-09-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reasoncategorie', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive Language'), ('spoiler', 'Spoilers')], max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviewapp.review')),
            ],
            options={
                'unique_together': {('reported_review',)},
            },
        ),
    ]
