# Generated by Django 6.1 on 2026-09-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_cast_unique_together'),
        ('Reviewapp', '0002_reportreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='reportreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'Movie')},
        ),
        migrations.AlterField(
            model_name='reportreview',
            name='reported_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Reviewapp.review'),
        ),
        migrations.AlterUniqueTogether(
            name='reportreview',
            unique_together={('reported_review', 'report_user')},
        ),
    ]
