# Generated by Django 6.1 on 2026-09-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewapp', '0003_rename_user_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportreview',
            name='status',
            field=models.CharField(choices=[('pending', 'pendign'), ('dismissed', 'dismissed'), ('action_taken', 'action_taken')], default='pending'),
        ),
    ]
