# Generated by Django 6.1 on 2026-09-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewapp', '0004_reportreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreview',
            name='reported_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='Reviewapp.review'),
        ),
    ]
