# Generated by Django 6.1 on 2026-09-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_cast_unique_together'),
        ('Reviewapp', '0005_alter_reportreview_reported_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Adminapp.movie'),
        ),
    ]
