# Generated by Django 6.1 on 2026-08-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Synopsis', models.TextField()),
                ('Runtime', models.IntegerField()),
                ('Poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Released_date', models.DateField()),
                ('Director', models.CharField(max_length=100)),
                ('Genre_name', models.ManyToManyField(related_name='movies', to='Adminapp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character', models.CharField(max_length=100)),
                ('Actor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.actor')),
                ('Movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.movie')),
            ],
        ),
    ]
