# Generated by Django 6.1 on 2026-09-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('Actor_name', 'Movie_name')},
        ),
    ]
